"""
Aegis Dynamic RAG Engine.
Combines Hybrid Retrieval (BGE-small + BM25) with Grounded SLM Generation (Qwen-2.5-1.5B via llama.cpp).
Adheres strictly to the Three-Part Provenance Contract:
1. Direct Answer (Generated by Qwen strictly grounded in retrieved facts)
2. Verifiable Claims with Document/Page Provenance (Bound deterministically from cards)
3. Expressed Uncertainties & Gaps (Zero-Hallucination Guardrails)
"""

import os
import sys
import time
from typing import Dict, Any, List

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from llama_cpp import Llama
from src.retriever import HybridRetriever

class AegisRAGEngine:
    def __init__(
        self,
        cards_path: str = "knowledge_cards.json",
        model_path: str = "models/qwen2.5-1.5b-instruct-q4_k_m.gguf",
        confidence_threshold: float = 0.50,
        n_threads: int = 8
    ):
        print("="*70)
        print("INITIALIZING AEGIS DYNAMIC RAG ENGINE")
        print("="*70)

        # 1. Initialize Hybrid Retriever (BGE-small + BM25)
        self.retriever = HybridRetriever(cards_path=cards_path)
        self.threshold = confidence_threshold

        # 2. Initialize Qwen-2.5-1.5B SLM via llama.cpp
        print(f"\nLoading Qwen-2.5-1.5B from '{model_path}' (Threads: {n_threads})...")
        t0 = time.time()
        self.llm = Llama(
            model_path=model_path,
            n_ctx=2048,
            n_threads=n_threads,
            verbose=False
        )
        print(f"Qwen-2.5-1.5B SLM loaded and ready in {time.time() - t0:.2f} seconds.")
        print("="*70)

    def answer_question(self, question: str) -> Dict[str, Any]:
        """
        End-to-End Dynamic RAG Pipeline:
        1. Hybrid Search (BGE + BM25)
        2. Anti-Hallucination Confidence Gate
        3. Grounded Generation via Qwen-1.5B
        4. Deterministic Provenance Binding
        """
        # Step 1: Hybrid Search
        matches = self.retriever.search_hybrid(question, top_k=2)
        top_match = matches[0]
        top_card = top_match["card"]
        top_score = top_match["score"]

        # Step 2: Anti-Hallucination Confidence Gate (Rejects off-topic / generic queries)
        if top_score < self.threshold:
            return {
                "question": question,
                "status": "UNDETERMINED",
                "direct_answer": "The requested information could not be determined from the indexed Aegis Series-7 HCS knowledge store.",
                "claims": [],
                "conflicts_or_version_scopes": [],
                "uncertainties_or_gaps": [
                    f"Out of scope or low retrieval confidence (Top score: {top_score:.3f} < threshold: {self.threshold:.2f})."
                ],
                "retrieved_card": None,
                "retrieval_score": top_score
            }

        # Step 3: Handle Registered Documentation Gaps / False Premises
        if top_card.get("is_gap", False):
            return {
                "question": question,
                "status": "UNDETERMINED",
                "direct_answer": top_card["facts"],
                "claims": [
                    {
                        "claim": top_card["facts"],
                        "provenance": p,
                        "trust_tier": p.get("trust_tier", "Tier 2")
                    }
                    for p in top_card.get("provenance", [])
                ],
                "conflicts_or_version_scopes": [],
                "uncertainties_or_gaps": [
                    top_card.get("gap_reason", "Official documentation gap or false premise detected.")
                ],
                "retrieved_card": top_card["card_id"],
                "retrieval_score": top_score
            }

        # Step 4: Grounded SLM Generation via Qwen-2.5-1.5B
        prompt = (
            "<|im_start|>system\n"
            "You are an industrial safety and engineering assistant for the Aegis Series-7 Hydraulic Control System. "
            "Answer the user's question directly, accurately, and thoroughly using ONLY the provided Context facts. "
            "Ensure you explicitly include all relevant document names exactly as formatted (e.g. ECN-1042 with hyphen, not ECN 1042), "
            "specific subsystem locations (e.g. Coolant Loop, Skid B), "
            "and voltage or pressure ratings (e.g. 480V, 180 bar, 200 bar) mentioned in the Context. "
            "Never extrapolate or invent facts outside the Context.<|im_end|>\n"
            "<|im_start|>user\n"
            f"Context:\n{top_card['facts']}\n\n"
            f"Question:\n{question}<|im_end|>\n"
            "<|im_start|>assistant\n"
        )

        response = self.llm(
            prompt,
            max_tokens=220,
            temperature=0.0,  # Greedy deterministic decoding
            stop=["<|im_end|>", "\n\n\n"]
        )

        direct_answer = response["choices"][0]["text"].strip()

        # Step 5: Deterministic Provenance Binding
        claims = []
        for p in top_card.get("provenance", []):
            claims.append({
                "claim": top_card["facts"],
                "provenance": p,
                "trust_tier": p.get("trust_tier", "Tier 2")
            })

        conflicts = []
        if "version_scope" in top_card:
            conflicts.append(top_card["version_scope"])

        status = "ANSWERED_WITH_VERSION_SCOPE" if conflicts else "ANSWERED"

        return {
            "question": question,
            "status": status,
            "direct_answer": direct_answer,
            "claims": claims,
            "conflicts_or_version_scopes": conflicts,
            "uncertainties_or_gaps": [],
            "retrieved_card": top_card["card_id"],
            "retrieval_score": top_score
        }

if __name__ == "__main__":
    engine = AegisRAGEngine()

    test_questions = [
        "alarm a17 10 second",
        "What must be true before starting the hydraulic power system?",
        "What voltage does transformer T1 step down?",
        "Who approved engineering bulletin ECN-1058?",
        "What is the capital of France?"
    ]

    print("\n" + "="*80)
    print("END-TO-END RAG ENGINE INFERENCE TESTS")
    print("="*80)

    for q in test_questions:
        print(f"\n[QUERY]: \"{q}\"")
        t0 = time.time()
        res = engine.answer_question(q)
        elapsed = time.time() - t0

        print(f"  Status:       {res['status']}")
        print(f"  Latency:      {elapsed:.3f} s")
        print(f"  Score:        {res['retrieval_score']:.4f} (Card: {res['retrieved_card']})")
        print(f"  Direct Answer:\n    {res['direct_answer']}")
        if res['claims']:
            docs = [c['provenance']['document'] for c in res['claims']]
            print(f"  Provenance:   {', '.join(docs)}")
        if res['uncertainties_or_gaps']:
            print(f"  Disclosures:  {res['uncertainties_or_gaps'][0]}")
        print("-" * 80)
